### ISSUE TITLE
Panick in debug/unsoundness in release

### ISSUE THREAD

**Issue by mexus** [JackThomson2/wyhash2#1]
When a bytes array we need to hash is longer than 8 but shorter than 17 bytes, the crate tries to split the original array into two 8-bytes array, which is impossible: https://github.com/JackThomson2/wyhash2/blob/46c1c8978ac6387a197e21b29956a368a4415f70/src/lib.rs#L86

I don't know which would be the correct way to solve the issue, but currently running the code on arbitrary data produces undefined behavior in release mode :(

I also propose to add some fuzzy testing to the project in order to discover such cases early during development. For example, the following simple test
```rust
#[quickcheck_macros::quickcheck]
fn random_check(name: Vec<u8>) {
    wyhash2::wyhash_single(&name, 0);
}
```
would have helped to discover the problem immediately :)

**Comment by JackThomson2** [comment]
Hi Mexus, thanks for spotting this. I'll submit a patch for this ASAP, some fuzzing would also be a great idea.

**Comment by mexus** [comment]
Wow, thanks for such a fast response! :)

And why are we still there, isn't there also a similar problem at the unsafe block at https://github.com/JackThomson2/wyhash2/blob/master/src/lib.rs#L130 ? For example, when an array length is 17..

**Comment by JackThomson2** [comment]
I have a fix for the initial issue, I simply needed to do ```len() -8..```  rather than ```len() - 9..``` this way we're catching the last 8 elements of the array this will be fine if the array is less than 16 as the two arrays will overlap.

Thanks for the second report I'll get that resolved now

**Comment by mexus** [comment]
Sounds great, thanks!

**Comment by JackThomson2** [comment]
Hi Mexus, thank you so much for trying the library, I've pushed a new update which should hopefully fix the issues you outlined! 👍

**Comment by mexus** [comment]
Yay, tests pass!

Thanks a lot for a blazing fast hashing library and even faster help :))

Btw, are you going to publish an update to crates.io any time soon?

**Comment by JackThomson2** [comment]
Great I'm glad it's all working for you! Thank you for such a helpful issue report.

Version 2.1 is now live crates.io for you now 🚀

**Comment by JackThomson2** [comment]
I've now yanked version 0.2.0 from crates.io down to unsoundness.

**Comment by mexus** [comment]
You rock :guitar: !
